# Generated by Django 4.0.6 on 2022-07-17 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flote',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=30)),
                ('patent', models.CharField(max_length=20)),
                ('engine_n', models.IntegerField()),
                ('chassis_n', models.IntegerField()),
                ('production_year', models.DateField()),
                ('status', models.IntegerField()),
                ('justifyStatus', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('name', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mantenance', models.BooleanField()),
                ('date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('cost', models.FloatField()),
                ('flote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.flote')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
