# Generated by Django 4.0.6 on 2022-08-15 22:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flote',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('characteristics', models.CharField(max_length=600)),
                ('patent', models.CharField(max_length=20)),
                ('production_year', models.DateField(blank=True, null=True)),
                ('engine_number', models.IntegerField(blank=True, null=True)),
                ('chassis_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('GRE', 'GREEN'), ('YEL', 'YELLOW'), ('RED', 'RED')], max_length=30)),
                ('justifyStatus', models.CharField(blank=True, default='', max_length=600)),
                ('operators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('views', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REP', 'REPAIR'), ('MAN', 'MAINTENANCE')], max_length=30)),
                ('date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('description', models.CharField(max_length=600)),
                ('cost', models.FloatField()),
                ('flote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.flote')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
