# Generated by Django 4.0.6 on 2022-07-17 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flote',
            name='operator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='polls.operator'),
        ),
    ]
